### PR TITLE
Draft: PaymentService

### PR DESCRIPTION
**Pull request by fxbrit**
todo:
- [x] fix `PaymentResponseConsumer.kt` causing an exception when trying to forward to another topic:
  - I couldn't find the root cause so far, to reproduce ` curl -H "Content-Type: application/json" -d '{"paymentId":10, "status":1}' localhost:8080/tests/reponseFromBank`;
  - once fixed the same approach should be used in `PaymentRequestConsumer.kt`, so that the full Kafka stack is ready;
- [x] interaction with the database;
- [ ] randomize response from Bank;
- [ ] testing;

at the end it's worth to re-test with the testing controller I implemented.

### CODE REVIEW

**Comment by Ale142** [comment]
> turns out it can't be done in private repos, **please do NOT merge**.

I

**Comment by Ale142** [comment]
I've changed the repository visibility, now It's possible to change PR to draft

**Comment by fxbrit** [comment]
thanks!

**Review by luco5826 — APPROVED** [review]

**Comment by fxbrit** [comment]
oh yes, squash..

**Pull request merged**
